# version: 2
# updates:
# - package-ecosystem: pip
#   directory: "/"
#   schedule:
#     interval: daily
#     time: "08:00"
#   open-pull-requests-limit: 99
#   ignore:
#   - dependency-name: pylint
#     versions:
#     - 2.7.0
#     - 2.7.2
#     - 2.7.4
#     - 2.8.1
#   - dependency-name: sqlalchemy
#     versions:
#     - 1.4.5
#     - 1.4.6
#     - 1.4.7
#     - 1.4.8
#     - 1.4.9
#   - dependency-name: importlib-metadata
#     versions:
#     - 3.10.1
#     - 3.9.0
#     - 3.9.1
#     - 4.0.0
#   - dependency-name: xlsxwriter
#     versions:
#     - 1.3.9
#   - dependency-name: astroid
#     versions:
#     - 2.5.3
#   - dependency-name: identify
#     versions:
#     - 2.0.0
#     - 2.2.3
#   - dependency-name: fbs
#     versions:
#     - 0.9.3
#   - dependency-name: scipy
#     versions:
#     - 1.6.2
#   - dependency-name: pandas
#     versions:
#     - 1.2.3
#   - dependency-name: itur
#     versions:
#     - 0.3.0
#   - dependency-name: pyinstaller
#     versions:
#     - "4.2"
#   - dependency-name: pre-commit
#     versions:
#     - 2.12.0
#   - dependency-name: matplotlib
#     versions:
#     - 3.4.0
#   - dependency-name: elevation
#     versions:
#     - 1.1.2
#   - dependency-name: sip
#     versions:
#     - 6.0.3
