# Request constants
REQUEST_ERROR = 1
INVALID_UF = 2

# Settings table constants
CURRENT_UF_ID = 'CURRENT_UF_ID'
CURRENT_COUNTY_ID = 'CURRENT_COUNTY_ID'
COLOR_MAP_SIMULATION = 'COLOR_MAP_SIMULATION'
LAST_DATABASE_UPDATE = 'LAST_DATABASE_UPDATE'

# Lat longs
UFLA_LAT_LONG_POSITION = (-21.226244, -44.978407)
