on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Multi Platform

jobs:
  build-linux:
    name: Create Release and Upload Asset Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release  # Creates the release, assets will be added after building
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # body: ""  # release message, alternative to body_path
          body_path: release_text.md  # uncomment if not used
          draft: false
          prerelease: false
      - name: Install fpm (required for fbs)
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          fpm --version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fbs
        run: |
          fbs freeze
          fbs installer
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/analysys_of_coverage_antenna.deb
          asset_name: analysys_of_coverage_antenna.deb
          tag: ${{ github.ref }}
          overwrite: true

  build-macos:
    name: Upload Release Asset macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fbs
        run: |
          fbs freeze
          fbs installer
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/analysys_of_coverage_antenna.dmg
          asset_name: analysys_of_coverage_antenna.dmg
          tag: ${{ github.ref }}
          overwrite: true

  build-windows:
    name: Upload Release Asset
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fbs and freeze application
        run: |
          fbs freeze
          fbs installer
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/analysys_of_coverage_antennaSetup.exe
          asset_name: analysys_of_coverage_antennaSetup.exe
          tag: ${{ github.ref }}
          overwrite: true